=== AlexVolkow/MetaMusic/test/src/data/xml/metamusic-repository.dtd
<!--

   DTD for MetaMusic repository XML im- and exports

   @author Christian Pesch
   @version $Id: metamusic-repository.dtd 477 2005-01-19 18:03:59Z cpesch $

 -->

<!ELEMENT repository ( artist | composition | genre | group | location | media | track | user )*>

<!ELEMENT artist ( creationUser | genre | modificationUser )*>
<!ATTLIST artist musicBrainzId CDATA #IMPLIED
                 creationDate CDATA #IMPLIED
                 homepage CDATA #IMPLIED
                 id ID #REQUIRED
                 modificationDate CDATA #IMPLIED
                 name CDATA #IMPLIED
>

<!ELEMENT composition ( contribution | creationUser | genre | modificationUser | part )*>
<!ATTLIST composition musicBrainzId CDATA #IMPLIED
                      cover CDATA #IMPLIED
                      creationDate CDATA #IMPLIED
                      id ID #IMPLIED
                      modificationDate CDATA #IMPLIED
                      name CDATA #IMPLIED
                      ref IDREF #IMPLIED
                      seconds CDATA #IMPLIED
                      recordingDate CDATA #IMPLIED
>

<!ELEMENT contribution ( contributor, piece, role )>

<!ELEMENT contributor EMPTY>
<!ATTLIST contributor ref IDREF #REQUIRED
>

<!ELEMENT creationUser EMPTY>
<!ATTLIST creationUser ref IDREF #REQUIRED
>

<!ELEMENT exportGenre EMPTY>
<!ATTLIST exportGenre ref IDREF #REQUIRED
>

<!ELEMENT genre ( creationUser | modificationUser | exportGenre | specialisation )*>
<!ATTLIST genre creationDate CDATA #IMPLIED
                id ID #IMPLIED
                modificationDate CDATA #IMPLIED
                name CDATA #IMPLIED
                ref IDREF #IMPLIED
>

<!ELEMENT group ( creationUser | genre | member | membership | modificationUser )*>
<!ATTLIST group musicBrainzId CDATA #IMPLIED
                creationDate CDATA #IMPLIED
                homepage CDATA #IMPLIED
                id ID #IMPLIED
                modificationDate CDATA #IMPLIED
                name CDATA #IMPLIED
                ref IDREF #IMPLIED
>

<!ELEMENT location ( composition | creationUser | modificationUser | track )*>
<!ATTLIST location musicBrainzId CDATA #IMPLIED
                   VBR CDATA #IMPLIED
                   bitRate CDATA #IMPLIED
                   creationDate CDATA #IMPLIED
                   format CDATA #IMPLIED
                   id ID #IMPLIED
                   modificationDate CDATA #IMPLIED
                   name CDATA #IMPLIED
                   ref IDREF #IMPLIED
                   sampleFrequency CDATA #IMPLIED
                   tagDate CDATA #IMPLIED
>

<!ELEMENT media ( creationUser | location | modificationUser | owner )*>
<!ATTLIST media available CDATA #IMPLIED
                creationDate CDATA #IMPLIED
                id ID #REQUIRED
                modificationDate CDATA #IMPLIED
                name CDATA #IMPLIED
                type CDATA #IMPLIED
>

<!ELEMENT member EMPTY>
<!ATTLIST member ref IDREF #REQUIRED
>

<!ELEMENT membership ( group, member )>

<!ELEMENT modificationUser EMPTY>
<!ATTLIST modificationUser ref IDREF #REQUIRED
>

<!ELEMENT owner EMPTY>
<!ATTLIST owner ref IDREF #REQUIRED
>

<!ELEMENT part ( portion, whole )>
<!ATTLIST part index CDATA #IMPLIED
>

<!ELEMENT piece EMPTY>
<!ATTLIST piece ref IDREF #REQUIRED
>

<!ELEMENT portion EMPTY>
<!ATTLIST portion ref IDREF #REQUIRED
>

<!ELEMENT role EMPTY>
<!ATTLIST role name ID #IMPLIED
               ref IDREF #IMPLIED
>

<!ELEMENT specialisation EMPTY>
<!ATTLIST specialisation ref IDREF #REQUIRED
>

<!ELEMENT track ( contribution | creationUser | genre | modificationUser )*>
<!ATTLIST track musicBrainzId CDATA #IMPLIED
                creationDate CDATA #IMPLIED
                id ID #IMPLIED
                lyrics CDATA #IMPLIED
                modificationDate CDATA #IMPLIED
                name CDATA #IMPLIED
                ref IDREF #IMPLIED
                seconds CDATA #IMPLIED
                recordingDate CDATA #IMPLIED
>

<!ELEMENT user ( creationUser | modificationUser )*>
<!ATTLIST user EMail CDATA #IMPLIED
               creationDate CDATA #IMPLIED
	       enabled CDATA #IMPLIED
               fullName CDATA #IMPLIED
               id ID #REQUIRED
               locale CDATA #IMPLIED
               modificationDate CDATA #IMPLIED
               name CDATA #IMPLIED
               password CDATA #IMPLIED
>

<!ELEMENT whole EMPTY>
<!ATTLIST whole ref IDREF #REQUIRED
>

=== AlexVolkow/MetaMusic/test/src/data/xml/contributor-parsing.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<!-- MetaMusic repository XML export of duplicates -->

<repository>
  <artist id="_1"
          name="A VERY LONG AND STUPID NAME IN UPPERCASE"/>
  <artist id="_2"
          name="a very long but silly name in lowercase"/>
  <artist id="_3"
          name="REM"/> <!-- an abbreviation -->

  <artist id="_10"
          name="A &amp; B"/>
  <artist id="_11"
          name="C&amp; D"/>
  <artist id="_12"
          name="E &amp;F"/>
  <artist id="_13"
          name="G and H"/>
  <artist id="_14"
          name="I And J"/>
  <artist id="_15"
          name="K und L"/>
  <artist id="_16"
          name="M Und N"/>
  <artist id="_17"
          name="Mundstuhl"/> <!-- a name -->

  <artist id="_20"
          name="O feat P"/>
  <artist id="_21"
          name="Q feat.R"/>
  <artist id="_22"
          name="S Featuring T"/>
  <artist id="_23"
          name="UfeaturingSomebody"/> <!-- a name -->

  <track id="_30"
         name="T1 (feat U)"/>
  <track id="_31"
         name="T2 (feat. V)"/>
  <track id="_32"
         name="T3 (Featuring W)"/>

  <track id="_40"
         name="T4 (with X)"/>
  <track id="_41"
         name="T5 (With Y)"/>
</repository>

=== AlexVolkow/MetaMusic/test/src/data/xml/location-constraints.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<!-- MetaMusic repository XML export of duplicates -->

<repository>
  <track id="_1"
         name="Track"/>

  <composition id="_2" 
               name="Composition">
    <part index="3">
      <portion ref="_1"/>
      <whole ref="_2"/>
    </part>
  </composition>
  
  <media id="_4" name="Media">
    <location ref="_5"/>
  </media>

  <location id="_5"
            name="Location">
    <composition ref="_2"/>
    <track ref="_1"/>
  </location>
</repository>

=== AlexVolkow/MetaMusic/test/src/data/xml/predefined-genres.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<!-- MetaMusic repository XML export of the ID3 genres -->

<repository>

  <!-- predefined genres -->
  <genre id="_1027"
    name="Unknown"/>

  <genre id="_1028"
    name="Speech"/>

  <genre id="_1000"
    name="H&#x00f6;rbuch">
    <exportGenre ref="_1028"/>
  </genre>

  <genre id="_1001"
    name="Lesung">
    <exportGenre ref="_1028"/>
    <specialisation ref="_1002"/>
  </genre>

  <genre id="_1002"
    name="Lesung (de)">
    <exportGenre ref="_1028"/>
  </genre>

  <genre id="_1018"
    name="Folk">
    <specialisation ref="_1019"/>
  </genre>

  <!-- music brainz II genres -->
  <genre id="_1017"
    name="Rock">
    <specialisation ref="_1019"/>
  </genre>
  <genre id="_1021"
    name="Classic">
    <specialisation ref="_1016"/>
    <specialisation ref="_1015"/>
  </genre>
  <genre id="_1022"
    name="Jazz"/>
  <genre id="_1023"
    name="Blues"/>
  <genre id="_1024"
    name="Country"/>

  <genre id="_1016"
    name="Piano"/>
  <genre id="_1015"
    name="Symphony"/>
  <genre id="_1014"
    name="Heavy Metal"/>
  <genre id="_1013"
    name="Punk"/>
  <genre id="_1012"
    name="Acoustic"/>

  <!-- specialisations -->
  <genre id="_1019"
    name="Folk-Rock"/>

  <user id="_1999"
    name="cpesch"/>
</repository>

=== AlexVolkow/MetaMusic/test/src/data/xml/unique-objects.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<!-- MetaMusic repository XML export of duplicates -->

<repository>
  <track id="_1"
         name="Track"/>
  <track id="_2"
         name="Track"/>
  <track id="_3"
         name="Track"/>
  <track id="_4"
         name="Track"/>
  <track id="_5"
         name="Track"/>

  <media id="_11" name="Media">
    <location ref="_31"/>
    <location ref="_32"/>
    <location ref="_33"/>
    <location ref="_34"/>
    <location ref="_35"/>
  </media>

  <location id="_31"
            name="Location.mp3"/>
  <location id="_32"
            name="Location.mp3"/>
  <location id="_33"
            name="Location.mp3"/>
  <location id="_34"
            name="Location.mp3"/>
  <location id="_35"
            name="Location.mp3"/>
</repository>

=== AlexVolkow/MetaMusic/test/src/data/xml/predefined-artists.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<!-- MetaMusic repository XML export -->

<repository>

  <genre id="_1052"
         name="Electronic">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
  </genre>
  <genre id="_1017"
         name="Rock">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
  </genre>
  <genre id="_1019"
         name="Folk-Rock">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
  </genre>

  <artist id="_1009"
          name="Brian Adams">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
    <genre ref="_1017"/>
  </artist>

  <artist id="_1008"
          name="Dave Gahan">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
  </artist>
  <group id="_1001"
         name="Depeche Mode">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
    <genre ref="_1052"/>
    <member ref="_1008"/>
  </group>

  <artist id="_1007"
          name="Mark Knopfler">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
    <genre ref="_1019"/>
  </artist>
  <group id="_1004"
         name="Dire Straits">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
    <genre ref="_1017"/>
    <member ref="_1007"/>
  </group>

  <artist id="_1006"
          name="Michael Stipe">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
  </artist>
  <group homepage="http://www.rem.org"
         id="_1003"
         name="R.E.M.">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
    <genre ref="_1017"/>
    <member ref="_1006"/>
  </group>

  <group id="_1010"
          name="Various"
          musicBrainzId="89ad4ac3-39f7-470e-963a-56509c546377">
    <creationUser ref="_1999"/>
    <modificationUser ref="_1999"/>
  </group>

  <user id="_1999"
    name="cpesch"/>
</repository>

=== AlexVolkow/MetaMusic/test/src/data/xml/genre-user.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<!-- MetaMusic repository XML export of genre and user -->

<repository>

  <user creationDate="08.08.2008 08:08:08"
        EMail="a@localhost"
        fullName="a"
        id="_4711"
        locale="en"
        modificationDate="09.09.2009 09:09:09"
        name="a"
        password="a">
    <creationUser ref="_4711"/>
    <modificationUser ref="_4711"/>
  </user>

  <genre creationDate="10.10.2010 10:10:10"
         id="_4712"
         modificationDate="07.07.2007 07:07:07"
         name="c">
    <creationUser ref="_4711"/>
    <modificationUser ref="_4714"/>
  </genre>
  <genre creationDate="06.06.2006 06:06:06"
         id="_4713"
         modificationDate="11.11.2011 11:11:11"
         name="d">
    <creationUser ref="_4711"/>
    <modificationUser ref="_4714"/>
    <specialisation ref="_4712"/>
  </genre>

  <user creationDate="05.05.2005 05:05:05"
        EMail="b@localhost"
        fullName="b"
        id="_4714"
        locale="de"
        modificationDate="12.12.2012 12:12:12"
        name="b"
        password="b">
    <creationUser ref="_4711"/>
    <modificationUser ref="_4711"/>
  </user>

</repository>

=== AlexVolkow/MetaMusic/test/src/data/xml/conflicting-compositions.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<repository>

  <artist creationDate="01.01.1998 01:02:03"
          homepage="http://www.anartist.com"
          id="_2005"
          modificationDate="01.08.2003 01:02:03"
          name="An artist"/>

  <artist creationDate="02.02.1999 02:03:05"
          homepage="http://www.anotherartist.com"
          id="_2006"
          modificationDate="02.09.2003 02:03:05"
          name="Another artist"/>

  <!-- this the original -->
  <composition creationDate="10.12.2003 15:45:09"
               id="_3476"
               modificationDate="10.12.2004 19:39:40"
               name="Album"
               recordingDate="20.02.2002 20:22:02">
    <contribution>
      <contributor ref="_2005"/>
      <piece ref="_3476"/>
      <role name="performer"/>
    </contribution>
  </composition>

  <!-- this one is conflicting -->
  <composition creationDate="20.12.2003 15:05:15"
               id="_3611"
               modificationDate="24.01.2004 17:49:42"
               name="Album"
               recordingDate="01.02.1999 03:04:05">
    <contribution>
      <contributor ref="_2005"/>
      <piece ref="_3611"/>
      <role ref="performer"/>
    </contribution>
  </composition>

  <!-- this one is conflicting -->
  <composition creationDate="15.12.2003 15:25:13"
               id="_3635"
               modificationDate="24.01.2004 17:59:31"
               name="Album"
               recordingDate="06.07.2000 08:09:10">
    <contribution>
      <contributor ref="_2005"/>
      <piece ref="_3635"/>
      <role ref="performer"/>
    </contribution>
  </composition>

  <!-- this one is ok -->
  <composition creationDate="10.12.2003 15:45:11"
               id="_3671"
               modificationDate="24.01.2004 18:23:12"
               name="Album"
               recordingDate="11.12.2001 13:14:15">
    <contribution>
      <contributor ref="_2006"/>
      <piece ref="_3671"/>
      <role ref="performer"/>
    </contribution>
  </composition>
</repository>

=== AlexVolkow/MetaMusic/test/src/data/xml/users.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE repository SYSTEM "metamusic-repository.dtd">

<!-- MetaMusic repository XML export of the users -->

<repository>

  <user creationDate="09.09.2003 19:25:12"
        EMail="root@localhost"
        fullName="Administrator"
        id="_2000"
        locale="en"
        modificationDate="09.09.2003 19:25:12"
        name="admin"
        password="admin"/>
  <user creationDate="26.04.1972 20:34:45"
        EMail="Christian_Pesch@gmx.de"
        fullName="Christian Pesch"
        id="_2150"
        locale="en"
        modificationDate="11.12.2003 17:39:41"
        name="cpesch"
        password="cpesch">
    <creationUser ref="_2000"/>
    <modificationUser ref="_2000"/>
  </user>
  <user creationDate="07.07.1977 16:45:07"
        fullName="Michael Stattmann"
        id="_2325"
        locale="at"
        modificationDate="11.12.2003 17:49:49"
        name="mstattma"
        password="mstattma">
    <creationUser ref="_2150"/>
    <modificationUser ref="_2150"/>
  </user>

</repository>
